services:
  db:
    image: postgres:14-alpine
    container_name: bang_dict_db
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    build: .
    container_name: bang_dict_app
    restart: always
    env_file: ./.env
    ports:
      - 8001:8000
      - 5557:5555
    volumes:
      - .:/app
    command: ["db", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - DB_HOST=db
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=5432

volumes:
  postgres_data:
