version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    build: .
    restart: always
    env_file: ./.env
    ports:
      - 8001:8000
      - 5557:5555
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=${{ secrets.POSTGRES_USER }}
      - DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - DB_NAME=${{ secrets.POSTGRES_DB }}
      - DB_PORT=5432

volumes:
  postgres_data:

