version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb_data:/data/db

  celerybackend:
    image: redis:latest
    ports:
      - 6378:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  web:
    depends_on:
      - mongodb
      - celerybackend
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8002:8000
      - 5557:5555
    volumes:
      - .:/app
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

volumes:
  mongodb_data:
