name: CI/CD for deploying the bangla dicitonary

on:
  push:
    branches: [main]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Restart Docker Compose
        uses: appleboy/ssh-action@master
        with:
        run: |
          cd ~/bang-dict-api/app/
          docker-compose down
          git pull
          docker-compose up --build -d
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_LOCAL_PORT: ${{ secrets.POSTGRES_LOCAL_PORT }}


  # Heavily modified deploy job to fit render.com
  deploy:
    name: Deploy
    needs: [test] # Our tests must pass in order to run the deploy job
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings