name: CI/CD for deploying the review-backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH into Server and Restart Docker Compose
      uses: appleboy/ssh-action@master
      with:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_LOCAL_PORT: ${{ secrets.POSTGRES_LOCAL_PORT }}
#        username: ${{ secrets.DROPLET_USERNAME }}
#        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd ~/bang-dict-api/app/
          docker-compose down
          git pull
          docker-compose up --build -d